const GAMES = [
  // Classic Arcade
  { id: 1, slug: "snake", name: "Snake", category: "Classic Arcade", difficulty: "Easy", emoji: "🐍", description: "Eat food to grow longer. Don't hit the walls or yourself!" },
  { id: 2, slug: "tetris", name: "Tetris", category: "Classic Arcade", difficulty: "Medium", emoji: "🟦", description: "Stack falling blocks to clear lines before they reach the top." },
  { id: 3, slug: "breakout", name: "Breakout", category: "Classic Arcade", difficulty: "Easy", emoji: "🧱", description: "Bounce the ball to break all bricks. Don't let it fall!" },
  { id: 4, slug: "pong", name: "Pong", category: "Classic Arcade", difficulty: "Easy", emoji: "🏓", description: "Classic table tennis. First to 7 wins!" },
  { id: 5, slug: "space-invaders", name: "Space Invaders", category: "Classic Arcade", difficulty: "Medium", emoji: "👾", description: "Shoot down waves of alien invaders before they reach Earth." },
  { id: 6, slug: "pacman", name: "Pac-Man", category: "Classic Arcade", difficulty: "Medium", emoji: "🟡", description: "Eat all dots while avoiding ghosts. Power-ups let you fight back!" },
  { id: 7, slug: "frogger", name: "Frogger", category: "Classic Arcade", difficulty: "Medium", emoji: "🐸", description: "Guide your frog across traffic and river to reach home safely." },
  { id: 8, slug: "asteroids", name: "Asteroids", category: "Classic Arcade", difficulty: "Medium", emoji: "☄️", description: "Shoot asteroids in space. Watch out — they split into smaller ones!" },
  { id: 9, slug: "galaga", name: "Galaga", category: "Classic Arcade", difficulty: "Hard", emoji: "🚀", description: "Defend against increasingly difficult alien formations." },
  { id: 10, slug: "centipede", name: "Centipede", category: "Classic Arcade", difficulty: "Hard", emoji: "🐛", description: "Shoot the centipede as it winds its way down the screen." },

  // Puzzle
  { id: 11, slug: "2048", name: "2048", category: "Puzzle", difficulty: "Easy", emoji: "🔢", description: "Slide tiles to combine numbers. Reach 2048 to win!" },
  { id: 12, slug: "minesweeper", name: "Minesweeper", category: "Puzzle", difficulty: "Medium", emoji: "💣", description: "Uncover all safe cells without triggering any mines." },
  { id: 13, slug: "sudoku", name: "Sudoku", category: "Puzzle", difficulty: "Medium", emoji: "🔢", description: "Fill the 9×9 grid so every row, column, and box has digits 1–9." },
  { id: 14, slug: "sokoban", name: "Sokoban", category: "Puzzle", difficulty: "Hard", emoji: "📦", description: "Push boxes onto target spots. Think carefully — you can't pull!" },
  { id: 15, slug: "nonogram", name: "Nonogram", category: "Puzzle", difficulty: "Hard", emoji: "🖼️", description: "Use number clues to reveal a hidden pixel picture." },
  { id: 16, slug: "lights-out", name: "Lights Out", category: "Puzzle", difficulty: "Medium", emoji: "💡", description: "Toggle lights to turn them all off. Each click affects neighbors too." },
  { id: 17, slug: "sliding-puzzle", name: "Sliding Puzzle", category: "Puzzle", difficulty: "Medium", emoji: "🔀", description: "Slide numbered tiles into correct order with only one empty space." },
  { id: 18, slug: "mastermind", name: "Mastermind", category: "Puzzle", difficulty: "Medium", emoji: "🎯", description: "Guess the secret color code using clues from each attempt." },
  { id: 19, slug: "tower-of-hanoi", name: "Tower of Hanoi", category: "Puzzle", difficulty: "Easy", emoji: "🗼", description: "Move disks to the target rod — never place a larger on a smaller." },
  { id: 20, slug: "pipe-puzzle", name: "Pipe Puzzle", category: "Puzzle", difficulty: "Medium", emoji: "🔧", description: "Rotate pipe pieces to connect the source to the drain." },
  { id: 21, slug: "color-sort", name: "Color Sort", category: "Puzzle", difficulty: "Easy", emoji: "🎨", description: "Sort colored liquids so each tube contains one color only." },
  { id: 22, slug: "ball-sort", name: "Ball Sort", category: "Puzzle", difficulty: "Medium", emoji: "🔵", description: "Sort colored balls into tubes — only matching colors stack." },
  { id: 23, slug: "block-puzzle", name: "Block Puzzle", category: "Puzzle", difficulty: "Easy", emoji: "🟫", description: "Drag blocks to fill complete rows and columns to clear them." },
  { id: 24, slug: "jigsaw", name: "Jigsaw Puzzle", category: "Puzzle", difficulty: "Easy", emoji: "🧩", description: "Drag and snap pieces together to complete the picture." },
  { id: 25, slug: "match3", name: "Match 3", category: "Puzzle", difficulty: "Easy", emoji: "💎", description: "Swap gems to match 3 or more in a row. Chain combos for big scores!" },

  // Card & Board
  { id: 26, slug: "solitaire", name: "Solitaire", category: "Card & Board", difficulty: "Medium", emoji: "🃏", description: "Classic Klondike solitaire. Build suit stacks from Ace to King." },
  { id: 27, slug: "freecell", name: "FreeCell", category: "Card & Board", difficulty: "Hard", emoji: "🂠", description: "Move all cards to foundations using four free cell spaces." },
  { id: 28, slug: "memory-match", name: "Memory Match", category: "Card & Board", difficulty: "Easy", emoji: "🀄", description: "Flip cards to find matching pairs. Remember what you've seen!" },
  { id: 29, slug: "blackjack", name: "Blackjack", category: "Card & Board", difficulty: "Easy", emoji: "🃏", description: "Get closer to 21 than the dealer without going over." },
  { id: 30, slug: "chess", name: "Chess", category: "Card & Board", difficulty: "Hard", emoji: "♟️", description: "Classic chess vs AI. Checkmate the king to win." },
  { id: 31, slug: "checkers", name: "Checkers", category: "Card & Board", difficulty: "Medium", emoji: "⚫", description: "Jump over opponent's pieces to capture them all." },
  { id: 32, slug: "reversi", name: "Othello / Reversi", category: "Card & Board", difficulty: "Medium", emoji: "⬛", description: "Flip your opponent's discs. Control the board to win." },
  { id: 33, slug: "mahjong", name: "Mahjong Solitaire", category: "Card & Board", difficulty: "Medium", emoji: "🀄", description: "Remove matching tile pairs from the pyramid until the board is clear." },
  { id: 34, slug: "video-poker", name: "Video Poker", category: "Card & Board", difficulty: "Medium", emoji: "🎰", description: "Draw cards to make the best poker hand and win credits." },
  { id: 35, slug: "go", name: "Go (9×9)", category: "Card & Board", difficulty: "Hard", emoji: "⚪", description: "Ancient strategy game. Surround territory to outscore your opponent." },
  { id: 36, slug: "chinese-chess", name: "Chinese Chess", category: "Card & Board", difficulty: "Hard", emoji: "🉐", description: "象棋 — Capture the opponent's General to win this 2000-year-old classic." },
  { id: 37, slug: "connect-four", name: "Connect Four", category: "Card & Board", difficulty: "Easy", emoji: "🔴", description: "Drop discs to connect four of your color in a row." },

  // Word & Trivia
  { id: 38, slug: "wordle", name: "Wordle", category: "Word & Trivia", difficulty: "Easy", emoji: "🔤", description: "Guess the 5-letter word in 6 tries. Colors reveal how close you are." },
  { id: 39, slug: "hangman", name: "Hangman", category: "Word & Trivia", difficulty: "Easy", emoji: "🪢", description: "Guess letters to reveal the hidden word before the man is hanged." },
  { id: 40, slug: "typing-speed", name: "Typing Speed", category: "Word & Trivia", difficulty: "Easy", emoji: "⌨️", description: "Type the passage as fast and accurately as you can. Measure your WPM!" },
  { id: 41, slug: "anagram", name: "Anagram", category: "Word & Trivia", difficulty: "Medium", emoji: "🔀", description: "Unscramble the letters to form a valid word. Beat the clock!" },
  { id: 42, slug: "word-search", name: "Word Search", category: "Word & Trivia", difficulty: "Easy", emoji: "🔍", description: "Find all hidden words in the letter grid." },
  { id: 43, slug: "crossword", name: "Crossword", category: "Word & Trivia", difficulty: "Hard", emoji: "📰", description: "Fill the crossword grid using clues across and down." },
  { id: 44, slug: "quiz", name: "Quiz Trivia", category: "Word & Trivia", difficulty: "Easy", emoji: "❓", description: "Answer 10 trivia questions across various topics. How many can you get?" },
  { id: 45, slug: "spelling-bee", name: "Spelling Bee", category: "Word & Trivia", difficulty: "Medium", emoji: "🐝", description: "Make words using only the 7 given letters. Must include the center letter!" },
  { id: 46, slug: "boggle", name: "Boggle", category: "Word & Trivia", difficulty: "Hard", emoji: "🎲", description: "Find as many words as possible in the 4×4 letter grid before time runs out." },
  { id: 47, slug: "word-chain", name: "Word Chain", category: "Word & Trivia", difficulty: "Medium", emoji: "🔗", description: "Each word must start with the last letter of the previous word. Don't repeat!" },

  // Action & Shooter
  { id: 48, slug: "flappy-bird", name: "Flappy Bird", category: "Action & Shooter", difficulty: "Medium", emoji: "🐦", description: "Tap to flap through gaps between pipes. One touch to fly, one mistake to fall." },
  { id: 49, slug: "dino-run", name: "Dino Run", category: "Action & Shooter", difficulty: "Easy", emoji: "🦕", description: "Jump over cacti and duck under pterodactyls. How far can you run?" },
  { id: 50, slug: "bullet-hell", name: "Bullet Hell", category: "Action & Shooter", difficulty: "Hard", emoji: "💥", description: "Dodge waves of enemy bullets in this intense shoot-'em-up." },
  { id: 51, slug: "whack-a-mole", name: "Whack-a-Mole", category: "Action & Shooter", difficulty: "Easy", emoji: "🔨", description: "Whack moles as they pop up. Faster and faster — don't miss!" },
  { id: 52, slug: "duck-hunt", name: "Duck Hunt", category: "Action & Shooter", difficulty: "Easy", emoji: "🦆", description: "Click to shoot ducks before they fly away. Don't waste shots!" },
  { id: 53, slug: "fruit-ninja", name: "Fruit Ninja", category: "Action & Shooter", difficulty: "Medium", emoji: "🍉", description: "Swipe to slice flying fruit. Avoid bombs!" },
  { id: 54, slug: "geometry-dash", name: "Geometry Dash", category: "Action & Shooter", difficulty: "Hard", emoji: "🔷", description: "Jump and fly through obstacle courses to the beat of the music." },
  { id: 55, slug: "space-shooter", name: "Space Shooter", category: "Action & Shooter", difficulty: "Medium", emoji: "🛸", description: "Pilot your ship and blast enemy waves in outer space." },
  { id: 56, slug: "missile-command", name: "Missile Command", category: "Action & Shooter", difficulty: "Medium", emoji: "🚀", description: "Intercept incoming missiles to protect your cities." },
  { id: 57, slug: "endless-runner", name: "Endless Runner", category: "Action & Shooter", difficulty: "Medium", emoji: "🏃", description: "Run forever, jump obstacles, collect coins. Beat your high score!" },
  { id: 58, slug: "turret", name: "Turret Defense", category: "Action & Shooter", difficulty: "Medium", emoji: "🎯", description: "Aim and shoot enemies approaching your base. Upgrade your turret!" },
  { id: 59, slug: "laser-cannon", name: "Laser Cannon", category: "Action & Shooter", difficulty: "Easy", emoji: "⚡", description: "Fire your laser to destroy all targets using ricochet and physics." },

  // Platform & Adventure
  { id: 60, slug: "platformer", name: "Platformer", category: "Platform & Adventure", difficulty: "Medium", emoji: "🎮", description: "Run, jump, and reach the flag. Classic side-scrolling platform action." },
  { id: 61, slug: "dungeon", name: "Dungeon Crawler", category: "Platform & Adventure", difficulty: "Hard", emoji: "⚔️", description: "Explore random dungeons, fight monsters, collect loot." },
  { id: 62, slug: "text-adventure", name: "Text Adventure", category: "Platform & Adventure", difficulty: "Easy", emoji: "📖", description: "A classic interactive fiction adventure. Your choices shape the story." },
  { id: 63, slug: "maze-runner", name: "Maze Runner", category: "Platform & Adventure", difficulty: "Easy", emoji: "🌀", description: "Navigate through procedurally generated mazes to find the exit." },
  { id: 64, slug: "escape-room", name: "Escape Room", category: "Platform & Adventure", difficulty: "Medium", emoji: "🔑", description: "Solve puzzles and find hidden clues to escape before time runs out." },
  { id: 65, slug: "visual-novel", name: "Visual Novel", category: "Platform & Adventure", difficulty: "Easy", emoji: "📚", description: "An interactive story with branching choices. Multiple endings await." },
  { id: 66, slug: "monster-catcher", name: "Monster Catcher", category: "Platform & Adventure", difficulty: "Medium", emoji: "👾", description: "Explore the world, catch monsters, and battle trainers." },
  { id: 67, slug: "treasure-hunt", name: "Treasure Hunt", category: "Platform & Adventure", difficulty: "Easy", emoji: "💎", description: "Follow clues and explore maps to find buried treasure." },
  { id: 68, slug: "ninja", name: "Ninja Platformer", category: "Platform & Adventure", difficulty: "Hard", emoji: "🥷", description: "Wall-jump, dash, and deflect projectiles in fast-paced ninja action." },
  { id: 69, slug: "cave-explorer", name: "Cave Explorer", category: "Platform & Adventure", difficulty: "Medium", emoji: "🕯️", description: "Explore dark caves, avoid hazards, and collect gems." },

  // Strategy
  { id: 70, slug: "tower-defense", name: "Tower Defense", category: "Strategy", difficulty: "Hard", emoji: "🏰", description: "Place towers to stop waves of enemies from reaching your base." },
  { id: 71, slug: "tic-tac-toe", name: "Tic-Tac-Toe", category: "Strategy", difficulty: "Easy", emoji: "❌", description: "Get three in a row against a smart AI opponent." },
  { id: 72, slug: "battleship", name: "Battleship", category: "Strategy", difficulty: "Medium", emoji: "🚢", description: "Place your fleet and sink the enemy's ships before they sink yours." },
  { id: 73, slug: "idle-clicker", name: "Idle Clicker", category: "Strategy", difficulty: "Easy", emoji: "👆", description: "Click to earn, buy upgrades, and watch your empire grow automatically." },
  { id: 74, slug: "hex-strategy", name: "Hex Strategy", category: "Strategy", difficulty: "Hard", emoji: "⬡", description: "Capture hexagonal territory to connect your sides of the board." },
  { id: 75, slug: "kingdom-builder", name: "Kingdom Builder", category: "Strategy", difficulty: "Hard", emoji: "👑", description: "Manage resources, build structures, and grow your medieval kingdom." },
  { id: 76, slug: "rock-paper-scissors", name: "Rock Paper Scissors", category: "Strategy", difficulty: "Easy", emoji: "✂️", description: "Best of 5 against the AI. Can you outsmart the computer?" },
  { id: 77, slug: "ant-colony", name: "Ant Colony", category: "Strategy", difficulty: "Medium", emoji: "🐜", description: "Simulate an ant colony. Direct workers to gather food and expand." },
  { id: 78, slug: "dice-war", name: "Dice War", category: "Strategy", difficulty: "Easy", emoji: "🎲", description: "Roll dice to conquer territories in this Risk-inspired quick game." },
  { id: 79, slug: "card-battle", name: "Card Battle", category: "Strategy", difficulty: "Medium", emoji: "🃏", description: "Build a deck and battle the AI. Play cards, cast spells, win!" },

  // Physics & Simulation
  { id: 80, slug: "angry-birds", name: "Angry Birds", category: "Physics & Simulation", difficulty: "Medium", emoji: "🐦", description: "Launch birds to demolish pig fortresses. Use the right bird for each shot!" },
  { id: 81, slug: "bouncing-balls", name: "Bouncing Balls", category: "Physics & Simulation", difficulty: "Easy", emoji: "🔵", description: "Shoot balls to match and pop groups of 3 or more." },
  { id: 82, slug: "sand-sim", name: "Sand Simulation", category: "Physics & Simulation", difficulty: "Easy", emoji: "⏳", description: "Draw with sand, water, fire, and more. Watch elements interact." },
  { id: 83, slug: "game-of-life", name: "Conway's Game of Life", category: "Physics & Simulation", difficulty: "Easy", emoji: "🧬", description: "Place cells and watch life evolve according to Conway's rules." },
  { id: 84, slug: "pendulum", name: "Pendulum Art", category: "Physics & Simulation", difficulty: "Easy", emoji: "⏱️", description: "Watch chaotic pendulums trace beautiful patterns over time." },
  { id: 85, slug: "gravity-sim", name: "Gravity Simulator", category: "Physics & Simulation", difficulty: "Medium", emoji: "🪐", description: "Place planets and watch gravity shape their orbits in real time." },
  { id: 86, slug: "particle-system", name: "Particle System", category: "Physics & Simulation", difficulty: "Easy", emoji: "✨", description: "Create dazzling particle effects with your mouse. Pure eye candy." },
  { id: 87, slug: "water-flow", name: "Water Flow", category: "Physics & Simulation", difficulty: "Medium", emoji: "💧", description: "Draw terrain and watch water flow realistically downhill." },
  { id: 88, slug: "domino", name: "Domino Effect", category: "Physics & Simulation", difficulty: "Easy", emoji: "🁣", description: "Place dominoes and tip the first one. Watch the chain reaction!" },
  { id: 89, slug: "ragdoll", name: "Ragdoll Drop", category: "Physics & Simulation", difficulty: "Easy", emoji: "🪆", description: "Drop ragdolls through obstacle courses. Physics chaos guaranteed." },

  // Creative & Art
  { id: 90, slug: "pixel-art", name: "Pixel Art Painter", category: "Creative & Art", difficulty: "Easy", emoji: "🖼️", description: "Paint pixel art on a grid canvas. Save and share your creations." },
  { id: 91, slug: "music-seq", name: "Music Sequencer", category: "Creative & Art", difficulty: "Easy", emoji: "🎵", description: "Click grid cells to compose a looping 8-bit melody." },
  { id: 92, slug: "kaleidoscope", name: "Kaleidoscope", category: "Creative & Art", difficulty: "Easy", emoji: "🔮", description: "Draw and watch symmetrical patterns mirror in real time." },
  { id: 93, slug: "fractal", name: "Fractal Explorer", category: "Creative & Art", difficulty: "Easy", emoji: "🌀", description: "Zoom deep into the Mandelbrot set and discover infinite complexity." },
  { id: 94, slug: "spirograph", name: "Spirograph", category: "Creative & Art", difficulty: "Easy", emoji: "⭕", description: "Create mesmerizing geometric patterns with virtual gears." },
  { id: 95, slug: "color-puzzle", name: "Color Mixing", category: "Creative & Art", difficulty: "Easy", emoji: "🎨", description: "Mix primary colors to match the target shade. Learn color theory!" },
  { id: 96, slug: "ascii-art", name: "ASCII Art", category: "Creative & Art", difficulty: "Easy", emoji: "💻", description: "Type to generate ASCII art. Convert text and images to ASCII." },
  { id: 97, slug: "emoji-puzzle", name: "Emoji Puzzle", category: "Creative & Art", difficulty: "Easy", emoji: "😀", description: "Guess the word, movie, or phrase from emoji clues." },

  // Memory & Reflex
  { id: 98, slug: "simon-says", name: "Simon Says", category: "Memory & Reflex", difficulty: "Easy", emoji: "🟢", description: "Repeat the growing color sequence. How long can your memory last?" },
  { id: 99, slug: "reaction-time", name: "Reaction Time", category: "Memory & Reflex", difficulty: "Easy", emoji: "⚡", description: "Click as fast as you can when the screen changes. Test your reflexes!" },
  { id: 100, slug: "color-memory", name: "Color Memory", category: "Memory & Reflex", difficulty: "Easy", emoji: "🌈", description: "Memorize the color pattern, then reproduce it from memory." },
  { id: 101, slug: "number-memory", name: "Number Memory", category: "Memory & Reflex", difficulty: "Medium", emoji: "🔢", description: "Memorize increasingly long number sequences. How far can you go?" },
  { id: 102, slug: "pattern-memory", name: "Pattern Memory", category: "Memory & Reflex", difficulty: "Medium", emoji: "🔲", description: "Watch the grid light up, then recreate the exact pattern." },
  { id: 103, slug: "rhythm-tap", name: "Rhythm Tap", category: "Memory & Reflex", difficulty: "Medium", emoji: "🥁", description: "Tap the keys in time with the beat. Stay on rhythm to score!" },
  { id: 104, slug: "speed-math", name: "Speed Math", category: "Memory & Reflex", difficulty: "Medium", emoji: "🧮", description: "Solve math problems as fast as possible. Beat the timer!" },
  { id: 105, slug: "visual-memory", name: "Visual Memory", category: "Memory & Reflex", difficulty: "Hard", emoji: "👁️", description: "Memorize which squares light up, then click them all from memory." },

  // 2-Player Local
  { id: 106, slug: "pong-2p", name: "Pong 2-Player", category: "2-Player Local", difficulty: "Easy", emoji: "🏓", description: "Classic Pong for two players on one keyboard. First to 7 wins!" },
  { id: 107, slug: "air-hockey", name: "Air Hockey", category: "2-Player Local", difficulty: "Easy", emoji: "🏒", description: "Flick the puck into your opponent's goal. Fast and frantic!" },
  { id: 108, slug: "tank-battle", name: "Tank Battle", category: "2-Player Local", difficulty: "Medium", emoji: "🪖", description: "Two tanks, one arena. Dodge bullets and destroy your opponent!" },
  { id: 109, slug: "tic-tac-toe-2p", name: "Tic-Tac-Toe 2P", category: "2-Player Local", difficulty: "Easy", emoji: "⭕", description: "Classic Tic-Tac-Toe for two players. Get three in a row to win!" },
  { id: 110, slug: "mini-golf", name: "Mini Golf", category: "2-Player Local", difficulty: "Medium", emoji: "⛳", description: "Take turns putting through tricky mini-golf holes. Lowest score wins!" },
];

const CATEGORIES = [...new Set(GAMES.map(g => g.category))];
